name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: -----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCdPdtpdJHyUjTfpNuNoMAMAAAAGAAAAAEAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQDgCA8H1B103smuocFeKUXGbh2DOgGSdLGOw419UaD2lsNlI7GDe/DHerAvDlff/G8g031wuFtnfsT56dEwbyWiPlj1j0Q8eE5nHJg0gs8yDLcc49cFS0bfXyIhaLjYUXqvwxfTzyR1zjInd3JBuCbehNkzfD1QCbJmyjwfHzqiVWMhpFYpjUjcwXd1zjps4J0mQ99y96K9/tn40YNszIeE3Z3jqtCpIpGSgwYyJJdX+mN3oZCNLXuot/HgGAECBggEdFtz9q5EKwIuuiqTxOmkSKBSzBTbiPDX6TzDMKRF1Jk4kjkYCCGIrSuzQl1cwzgC6oG4KCD8CeRYuAZbyxJ1AAADwA3FlRXotTKXHn9ILFNKFkp7m4k2JGrvUf52JKRCOK1/qOVI7NCOHsFCn+IAZ9Y0H8klR5f/dXsPhExl26MFyVMmGrua8MagshNriXjDVC4JC0bcb1mlqvcG0/miy+PHcNMovrR07opUN/4u6E3LFo0OJlGBbJ8fI1otsXWQUq5zj3L47G7GsFIBL0HE+b0hPwOpSZEB8dsFSz5/UcU60zB5QUyuytziSieWwgY15T0oshgFR6SgQH7CF0WDJTj94w/NGhNQJ9jjdfNairBvbP/pkKR2RuKwWRizpoFuV98x3jIo+C6P6z9ZJE7FnG0EpcnO/LRgFvMs9/1PMXvb2skN6YRr4Ehl2R+lnbRziUuZ01oiBOFTksZLmgAv1dVxJywtVncEkf+96jybuauhx6K7JTNCBAlBlLcYtTnRie0DcJBheh0YJJHCWGnGBibt8Cpj7bLxadHMYvyT/3/RyPXvXpsJh7k/VXhyOIxpMnXLixLo9HheHlNu35BnH2ous1W4omj5jOk3KW87Jf95mFwrwZK7rtWQ4g5iZzTftCbCbuy2xOG8rpTvWzXVLPNFL+gn5R78xK4uNiSmh6lQrybn6vXhICzIJjhYbU4vCWcCwJ5i6XRC4C5ePr13ct3UNN/fF1G7jr7Aghke/sPyUSlUwMe1MKQbkMJa2I+llA8qhmMZ1cdSt3VnLaQFLLrWGgmAv/bYq54U/mB+bZSzNmjoB5X94lQ4dHQWk0Y5G/1dVpOI4+rMSBhojrdmeF4MJMdSvoctgYCNOJt/1IVTxqoJRf0+nCeQNLZz2E9sZ/kYmO8I+rsij+AVRhL3wXB7JuOALhHvl7H7xt99IQMHxw+KBT5/4y69SgiA6d2/81Df0GYTPPEQAYn7U2VAAfz8hWQXHJI0u+NpOq0n0F6A7HDJyf0R/hsq+oauuEYxrq9oseAxExU5wXQ8KV4olQDfTnay4E1zRsHfs14jq8IG8ISUHn+YBmkHoI9VyUBEs0OqRA9BSU4PXAqi5rXPxW+jFLS1bFm5pwoLuTrFq+BJ5KEu+Rvr6HE9ziuOkMoeajPzaZSJgoXSAVve1DQqFbKUYHFXMUWuT0W1adMoyLFulRHtDo2pi1DQaIv6wqdj9tk6AIzb+UIIQtgi0iJySRtF2OuDTQhQ4qtlqvN87+XZWvsVRpdKDfppHmwInL7jj9Nty5uudtpkjWh0jkgNKzEFZi5mKBVNhYrLogZtX4K+KUTw3/id93Q9EW8CMlOvqnmKudW00FWxZYF1z5jiixejkA==-----END OPENSSH PRIVATE KEY-----
        
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@34.87.23.65 << 'EOF'
          sudo git pull
          sudo docker stop ql_banhang_app
          sudo docker rm ql_banhang_app
          sudo docker --debug  build -t ql_banhang_app .
          sudo docker run --name ql_banhang_app -d --network=bridge -p 80:8080 ql_banhang_app
        EOF
